openapi: 3.0.0
info:
  title: Alphas Backtesting API
  version: 1.0.0
  description: API for backtesting trading alphas

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /instruments:
    get:
      summary: Get all available instruments
      responses:
        '200':
          description: List of instruments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Instrument'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /backtest:
    post:
      summary: Backtest alpha on given instruments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BacktestRequest'
      responses:
        '200':
          description: Backtest results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BacktestResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Instrument:
      type: object
      properties:
        figi:
          type: string
        ticker:
          type: string
        name:
          type: string
        currency:
          type: string
        lot:
          type: integer
        min_price_increment:
          type: number

    BacktestRequest:
      type: object
      required:
        - instruments
        - start_date
        - end_date
      properties:
        instruments:
          type: array
          items:
            type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date

    BacktestResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              instrument:
                type: string
              returns:
                type: number
              sharpe_ratio:
                type: number
              max_drawdown:
                type: number

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string 