services:
  backend:
    build: ./backend
    environment:
      - REDIS_URL=redis://redis
      - TINKOFF_TOKEN=${TINKOFF_TOKEN}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: 